import { Inter } from 'next/font/google'
import { CssBaseline, AppBar, Toolbar, Typography } from '@mui/material';
import apm from '../rum'
import { ApolloWrapper } from "@/lib/apollo-wrapper";


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
      <ApolloWrapper>
        <CssBaseline />
        <AppBar position="static">
          <Toolbar>
            <Typography variant="h6">
              ECO FOOD LINK
            </Typography>
          </Toolbar>
        </AppBar>

        {children}
        </ApolloWrapper>
      </body>

    </html>
  )
}
